frontend/package-lock.json
frontend/src/App.js
frontend/src/pages/Checkout.js

Decision made to use Stripe as the payment gateway, seems to be the most supported and easy to use
Decision made to use prebuilt checkout in the interest of saving time.
Checkout works by sending a POST which respoonds with a redirect to the desired checkout page

add checkout page

---

frontend/src/pages/Profile.js

Completed:
- Get current user data from database (one user only)
Next Steps:
- Fetch correct user data when user authentication system is finished

Uasc 38/profile data

---

frontend/src/App.js
frontend/src/components/AdminBookings.js
frontend/src/components/AdminRequests.js
frontend/src/components/Navbar.js
frontend/src/pages/Admin.js

Completed:
- Layout for the admin page is created with two separate components, requests and bookings.
Next steps:
- Create requests and bookings components

Created layout for admin dashboard

---

frontend/src/components/Navbar.css
frontend/src/components/Navbar.js

Code for navbar and code for displaying the necessary tabs in the nav bar.

Uasc 33/navbar display necessary tabs

---

frontend/package-lock.json
frontend/package.json
frontend/src/hooks/useAuthenticatedUser.js
frontend/src/pages/Home.js

Adds a new `useAuthenticatedUser` hook which returns both the Firebase user object and the associated user collection metadata document for the currently authenticated user.

Add persistent user data hook

---

frontend/src/components/ProfileCurrentBookings.js

Completed:
Created User Profile Request Change Modal.
Note:
This doesn't include any dynamic changes or data received from database. That will be done in a separate story.
To check this function out, go to the "/profile" link and click on the request change button.

Created User Request Change Modal

---

frontend/firestore.rules
frontend/src/components/BookingForm.js

closes #81 
Note: Line 133 uses "/users/SomeUserId" because I don't have an account that I can login with using the pre-production firestore
Next steps: Might needa make a slight change in the future to check for if the user is logged in when they try to submit a booking

Added functionality to post bookings to DB

---

.github/workflows/lint.yml
frontend/.eslintrc
frontend/package-lock.json
frontend/package.json
frontend/src/firebase.js
frontend/src/index.js
frontend/src/theme.js

Now prettier is ran as a step of ESLint.
Also adds a GitHub workflow to check ESLint when a PR is made.

Add prettier as step to eslintrc

---

frontend/.prettierrc
frontend/src/components/BookingForm.js
frontend/src/components/Navbar.js
frontend/src/hooks/useAuthenticatedUser.js

Uasc 90/authenticated user details

---

frontend/firestore.rules

Extends firestore read/write access until October 31st

Extend Firestore access to October 31st

---

frontend/src/App.js
frontend/src/components/AdminBookingDetails.js
frontend/src/components/AdminBookings.js
frontend/src/components/AdminDetailedBookings.js
frontend/src/components/AdminDetailedCalendar.js
frontend/src/pages/AdminBookingsDetailedView.js

- Added detailed calendar view that is accessible through the "Manage Bookings" button on the main Admin Dashboard
- Page contains a weekly calendar view that displays which users have bookings on each day
- When a user is clicked, it displays the check-in, check-out and total duration of the stay for that user
- Style of the page is consistent with the updated website styling
- Currently, the calendar only shows a weekly view. A possible next step could be to add a monthly view, or other views
- As a placeholder for demonstration purposes, the current check-out date is always three days after a check-in date. This will need to be changed based on the data that is passed to this function

UASC-52/Admin Bookings Calendar View

---

frontend/firestore.rules
frontend/src/components/ProfileBookingHistory.js
frontend/src/pages/Profile.js

There's an issue with the firestore.rules at the moment with the date being 9/30 in this version of the main. Apart from that, functionality should be working properly.

uasc-92/UserBooking-BookingHistory

---

client/src/firebase.ts
client/src/services/OpenApiFetchClient.ts

It is added to requests now as shown
Also added some error handling to the other network calls in the callback

Store jwt token in memory every time it refreshes

---

server/mock.txt
server/src/business-layer/utils/StripeService.ts
server/src/middleware/routes.test.ts
server/src/service-layer/controllers/StripeWebhook.ts

Changed StripeWebhook endpoint. 
Added metadata model

132-stripe-webhook-logic draft pr

---

client/src/components/generic/Dropdown/Dropdown.story.tsx
client/src/components/generic/Dropdown/Dropdown.tsx

Added dropdown component
https://github.com/UoaWDCC/uasc-web/assets/126216753/3f31a89b-99d5-4e95-ae18-96577f2377ee

260 create dropdown

---

server/src/business-layer/services/StripeService.ts

Added createProduct method in StripeService

---

client/src/components/generic/PageTitle/PageTitle.story.tsx
client/src/components/generic/PageTitle/PageTitle.tsx

304 page title component

---

client/src/components/composite/SignUpForm/PageConfig/PageConfig.tsx
client/src/components/composite/SignUpForm/Sections/SuccessSection.story.tsx
client/src/components/composite/SignUpForm/Sections/SuccessSection.tsx
client/src/components/composite/SignUpForm/SignUpForm.story.tsx
client/src/components/composite/SignUpForm/SignUpForm.tsx
client/src/components/composite/SignUpForm/utils/RouteNames.ts
client/src/components/composite/SignUpForm/utils/Utils.tsx

303 success section

---

client/src/assets/icons/hamburger.svg
client/src/components/composite/Navbar/Navbar.tsx
client/src/components/composite/Navbar/utils/LoginIndicator.tsx
client/src/components/composite/Navbar/utils/ProfileButton.tsx
client/src/components/composite/Navbar/utils/WrappedTab.tsx
client/src/components/generic/Tab/Tab.tsx
client/src/index.css

Have implemented the new design for mobile, made sure desktop doesn't break. Shadow colour also updated to reflect new design. 
This was done fully with media queries so there should be no performance hit that would occur from js-styling.
Most compact version
Normal mobile
Desktop

Implement mobile navbar

---

client/src/components/composite/SignUpForm/Sections/PaymentSection.tsx

374 restyle bank payment section

---

client/src/components/composite/Admin/AdminAvailabilityView/AdminAvailabilityView.tsx
client/src/components/composite/Navbar/Navbar.tsx

Straightfoward fixes:
- dont handle untruthy values in slot input
- listen for changes in current route (using `useLocation` hook)

Fix bad input and close navbar on route change

---

client/src/components/composite/SignUpForm/Sections/PaymentSection.tsx
client/src/components/generic/PricingCard/PricingCard.tsx

The home page was being overflowed by the pricing cards - with the payment screen also having some weird overflow issues. This ticket fixes those

fix overflow issues created by pricing cards

---

client/src/models/__generated__/schema.d.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/service-layer/controllers/PaymentController.ts
server/src/service-layer/request-models/UserRequests.ts

The frontend needed some more details from the backend such as:
- Retrieving existing sessions automatically
- Knowing type of error
This PR makes some small improvements so payment can be handled more smoothly on the front end

Booking payment endpoint frontend improvements

---

client/src/components/composite/Admin/AdminMemberView/ProtectedAdminMemberView.tsx
client/src/models/User.ts
client/src/models/__generated__/schema.d.ts
client/src/services/Admin/AdminMutations.ts
client/src/services/Admin/AdminQueries.ts
client/src/services/Admin/AdminUtils.test.ts
client/src/services/Admin/AdminUtils.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/service-layer/response-models/UserResponse.ts

add optimistic mutations to promote and demote user mutations

---

server/src/middleware/routes.test.ts
server/src/service-layer/controllers/BookingController.ts

Fixed small bug and wrote test to ensure it works

dont return dates with no members 

---

client/src/components/composite/SignUpForm/Sections/PaymentSection.tsx
client/src/components/composite/SignUpForm/utils/Utils.tsx

Now the membership type is not changed if they don't agree with the description of it

Add confirmation before user selects membership type

---

server/src/service-layer/controllers/BookingController.ts

This does not change any logic, just means that we can take advantage of concurrency and improve performance

replace for loop with Promise.all in fetch-users endpoint

---

client/src/components/generic/PricingBanner/PricingBanner.story.tsx
client/src/pages/Home/sections/utils/Pricing.ts
server/src/middleware/__generated__/swagger.json

change price on storybook

---

client/src/services/User/UserMutations.ts

Slow performance from password reset

remove blocking sign up

---

.github/workflows/deploy-client-production.yml
.github/workflows/deploy-server.production.yml

The GCP provider seems to require an actual env file to be created

Create env file properly

---

.github/workflows/deploy-server.production.yml

fix typo with production env variables

---

client/src/components/composite/SignUpForm/Sections/AccountSetupSection.tsx

Before it would just stay on the password reset form, now itll take them to the success page

Redirect user on password reset success

---

client/src/pages/Profile/Profile.tsx

edit icon removed for admin

---

client/src/components/composite/LoginForm/LoginForm.tsx
client/src/components/composite/LoginForm/PasswordResetForm/PasswordResetForm.tsx
client/src/pages/Login/Login.tsx
client/src/pages/Login/utils/Handlers.tsx

Now display the correct error message instead of `Unknown Error` (This handles the invalid email/password)

parse errors properly on log in form

---

client/src/components/composite/Booking/BookingInfoComponent/BookingInfoComponent.tsx

warning added

---

client/src/App.tsx
client/src/components/composite/Admin/AdminMemberView/ProtectedAdminMemberView.tsx
client/src/routes/routes.tsx

lazy loaded all non home pages, removed MUI remenants from `App.tsx`.
Also made sure to include a fallback loader for pages

Reduce main bundle from ~800kB to ~500kB

---

client/src/components/composite/Navbar/Navbar.tsx

fixed link

---

server/src/middleware/__generated__/swagger.json
server/src/service-layer/controllers/BookingController.ts
server/src/service-layer/controllers/PaymentController.ts

Right now it doesn't take this check into account, this mostly just copies the logic from #389. 
Also took initiative to display how long the user has to book, and also remind them of the dates they are booking

Minus off currently booked slots from availabilities

---

client/src/models/__generated__/schema.d.ts
server/src/business-layer/utils/StripeSessionMetadata.ts
server/src/middleware/__generated__/swagger.json
server/src/service-layer/controllers/BookingController.ts
server/src/service-layer/controllers/PaymentController.ts

Made sure that we display the correct dates, moved all info to metadata of stripe, #513 needs to be redone now

Refactor to store session dates in session metadata

---

client/src/components/composite/SignUpForm/Sections/PaymentSection.tsx

removed pay later link

---

client/src/components/generic/AboutSection/AboutSection.tsx
server/src/middleware/__generated__/swagger.json

removed fixed height

---

server/src/service-layer/controllers/PaymentController.ts

Before it was trying to parse undefined dates, now move that to after confirming there's an existing one

Allow existing sessions to be successfully found

---

client/src/components/generic/ModalContainer/ModalContainer.tsx

just made it so that the modal contents are actually hidden when we close it

fix cock blocking on admin booking view

---

client/src/components/composite/Admin/AdminBookingView/AdminBookingView.tsx
client/src/components/composite/Admin/AdminBookingView/WrappedAdminBookingView.tsx
client/src/components/utils/DateUtils.test.tsx
client/src/components/utils/DateUtils.tsx

Created new helper function to compare the dates, also closes #516

507 frontend sort bookings by date ascending on booking view

---

client/src/components/composite/Admin/AdminBookingView/AdminBookingView.tsx
client/src/components/composite/Admin/AdminBookingView/WrappedAdminBookingView.tsx
client/src/components/generic/ReusableTable/Table.tsx
client/src/models/__generated__/schema.d.ts
client/src/services/Admin/AdminMutations.ts
client/src/services/Admin/AdminService.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/service-layer/controllers/AdminController.ts
server/src/service-layer/response-models/BookingResponse.ts

Called the endpoint made in #408 
Also think we need to make the think a delete endpoint
https://github.com/UoaWDCC/uasc-web/assets/100653148/d5ee8ec8-33ed-4e99-8a13-fd15e283c7ed

allow admins to delete bookings on front end

---

client/src/pages/Profile/Profile.tsx
client/src/services/Booking/BookingQueries.ts
client/src/services/Booking/BookingService.ts

Makes use of the endpoint made in #338

Bookings table on profile

---

client/src/components/generic/Footer/Footer.tsx
client/src/pages/About.tsx

Before there were a lot of dead links. Now also keep all of them for mobile as well.

Improve footer links

---

client/src/components/composite/Admin/AdminMemberView/AdminMemberView.tsx
client/src/models/User.ts

For the UI design just decided to use a button that cycles through states

Allow sorting users by role on admin member view

---

client/src/pages/Home/Home.tsx
client/src/pages/Home/sections/utils/Pricing.ts

Will likely have to find a way to dynamically display this - for a future ticket

remove discount text on pricing section

---

client/src/components/composite/Admin/AdminMemberView/AdminMemberView.tsx
client/src/models/User.ts

Before choosing a filter will stop the data fetching

576 frontend keep fetching pages if there is a filter applied

---

uasc-next/environment.d.ts
uasc-next/next.config.mjs
uasc-next/src/app/sections/LandingSection.tsx
uasc-next/tailwind.config.ts

- Solved problem of css `url` not properly being appended with the base path
- Changed `a` tags to use the native next `Link`

Fix gh pages deployment issues

---

uasc-next/src/app/admin/layout.tsx
uasc-next/src/app/profile/page.tsx
uasc-next/src/components/composite/Admin/AdminBookingView/AdminBookingView.tsx

Now instead of flashing the admin/profile page, itll show the user a redirect before

display placeholder on protected routes to improve UX

---

uasc-next/src/app/admin/layout.tsx
uasc-next/src/components/composite/Admin/AdminBookingView/AdminBookingView.tsx
uasc-next/src/components/composite/Admin/AdminBookingView/WrappedAdminBookingView.tsx

Also allow the table to overflow on smaller screens for better UX

Add guest status to admin booking view

---

uasc-next/src/components/generic/ReusableTable/Table.tsx

remove wrapping on table to allow better ux on mobile

---

client/.storybook/main.ts

https://github.com/storybookjs/storybook/issues/21216#issuecomment-1513894759

fix storybook

---

client/.storybook/main.ts
client/package.json
client/src/components/generic/AboutSection/AboutSection.story.tsx

The config was working properly so #620 was not needed, however there were just some errors in the yarn installations

Revert changes in storybook fix pr

---

client/src/components/generic/EventsCard/EventsCard.story.tsx
client/src/components/generic/EventsCard/EventsCard.tsx

618 events card

---

client/sanity.config.ts
client/sanity/schema.ts
client/src/app/Home.story.tsx
client/src/app/HomeComponent.tsx
client/src/app/page.tsx
client/src/app/sections/AboutSection.tsx
client/src/app/sections/BenefitSection.tsx
client/src/app/sections/LandingSection.tsx
client/src/app/sections/PricingSection.story.tsx
client/src/app/sections/utils/Benefits.ts
client/src/components/generic/MemberBenefitCards/MemberBenefitCard.story.tsx
client/src/components/generic/MemberBenefitCards/MemberBenefitCard.tsx
client/src/components/utils/types.tsx
client/src/models/sanity/HomePage/Schema.ts
client/src/models/sanity/HomePage/Utils.ts

Could add customisable youtube video, but probably not needed rn
Will need to restyle the member benefit cards to use images instead of the icons later

make home page connected to CMS

---

client/sanity.config.ts
client/sanity/schema.ts
client/src/app/contact/page.tsx
client/src/components/composite/Contact/Contact.story.tsx
client/src/components/composite/Contact/Contact.tsx
client/src/components/composite/Contact/ContactDetailPanel/ContactDetailPanel.story.tsx
client/src/components/composite/Contact/ContactDetailPanel/ContactDetailPanel.tsx
client/src/components/generic/ContactDetail/ContactDetail.story.tsx
client/src/components/generic/ContactDetail/ContactDetail.tsx
client/src/components/generic/Footer/Footer.tsx
client/src/models/sanity/ContactDetail/Schema.ts
client/src/models/sanity/ContactDetail/Utils.ts

add contact page with dynamic details

---

client/src/components/composite/Navbar/Navbar.tsx

still has overflow-x issue on mobile #550

Remove pages from navbar that cause 404

---

.github/workflows/deploy-client-production.yml

Added cron job to deploy-client-production.yml

598 Create cron job to deploy frontend

---

package.json

570 neaten endpoint tests

---

server/src/data-layer/services/UserDataService.test.ts
server/src/middleware/tests/BookingController.test.ts
server/src/service-layer/controllers/BookingController.ts

There weren't a lot but good to maintain the backend every now and then!

456 Remove unneeded console.logs from back end

---

client/src/store/SignUpForm.tsx

Require at least 3 items split by a comma.

611 Signup validation

---

server/src/business-layer/services/StripeService.ts
server/src/service-layer/controllers/PaymentController.ts

Allow promo codes for lodge bookings

---

.github/workflows/deploy-client-production.yml
client/environment.d.ts
client/next.config.mjs
client/src/app/layout.tsx
client/src/app/robots.ts
client/src/app/sitemap.ts
client/tailwind.config.ts

this is important because we are going to be using a domain likely to be indexed by google.
see:
- https://nextjs.org/docs/app/api-reference/file-conventions/metadata/robots
- https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap
We make sure that these only allow indexing if 
- `NEXT_CONFIG_ENV`
- `FRONTEND_BASE_URL`
are set

add robots and sitemap generation

---

client/src/models/__generated__/schema.d.ts
server/src/middleware/__generated__/swagger.json
server/src/service-layer/controllers/BookingController.ts
server/src/service-layer/controllers/PaymentController.ts
server/src/service-layer/controllers/SignupController.ts
server/src/service-layer/controllers/StripeWebhook.ts
server/src/service-layer/controllers/UserController.ts

651 Document all backend endpoints

---

server/README.md

I hope I didn't misunderstand this ticket...
Created a README.md file with the Backend-Architecture part of the wiki.

671-readme-for-server

---

client/src/components/composite/Admin/AdminBookingView/AdminBookingView.tsx

for some reason the old one was being used causing it to be non-functional. 
Need to investigate how this happened in the first place

Use wrapped admin booking creation instead of plain one

---

client/src/components/generic/AlertsComponent/AlertsComponent.tsx
client/src/components/generic/Checkbox/Checkbox.tsx
client/src/components/generic/ContactDetail/ContactDetail.tsx
client/src/components/generic/Dropdown/Dropdown.tsx
client/src/components/generic/ExcitmentSlider/ExcitementSlider.tsx
client/src/components/generic/MenuList/MenuList.tsx
client/src/components/generic/MenuTab/MenuTab.tsx
client/src/components/generic/PasswordSetupForm/PasswordSetupForm.tsx
client/src/components/generic/PricingBanner/PricingBanner.tsx
client/src/components/generic/PricingCard/PricingCard.tsx
client/src/components/generic/ProfileInformationPanel/ProfileInformationPanel.tsx
client/src/components/generic/SignUpNotif/SignUpNotif.tsx
client/src/components/generic/StepperButtons/StepperButton.tsx
client/src/components/generic/StepperComponent/StepperComponent.tsx
client/src/components/generic/TextInputComponent/TextInput.tsx

avoided doing ones that were not in use (they probably need to be deleted in future tickets)

Document generic component props

---

client/src/components/composite/Contact/Contact.tsx

694 frontend fix overflox issue on contact page

---

client/src/components/composite/Admin/AdminAvailabilityView/AdminAvailabilityView.tsx

Had some issues with the way the start and end date were being checked - also memoized the data

Fix table on admin availability view

---

client/src/components/composite/Admin/AdminBookingView/AdminBookingCreationPopUp.tsx
client/src/components/composite/Admin/AdminBookingView/WrappedAdminBookingCreationPopUp.tsx

Added statuses:
- No results found
- Loading (has users to fetch)
Also fixed the search query not accounting for admins searching for full names

add indicators for statuses on admin booking creation

---

client/src/components/composite/LoginForm/LoginForm.tsx

add register button to login page

---

client/src/components/composite/LoginForm/LoginForm.tsx

Fixes issue introduced in https://github.com/UoaWDCC/uasc-web/pull/699#issuecomment-2254719594

wrap button in link to prevent submit handler being called

---

client/src/services/Admin/AdminMutations.ts

* invalidate booking availabilities after adding user
* update correct mutation :clown_face:
* invalidate seperately

Admin UX Release

---

server/src/business-layer/templates/BookingConfirmation.pug

> whoever is able to could you change the this line in ur confirmation email “UASC is stoked to confirm your booking for an unforgettable stay at your lodge between the nights of:” to
>“UASC is stoked to confirm your booking for an unforgettable stay at our lodge between:”

update booking confirmation template

---

server/src/service-layer/controllers/AdminController.ts

All functions should be relevantly tested in #737

call logging functions in the relevant endpoints

---

client/src/models/__generated__/schema.d.ts
server/src/data-layer/services/BookingHistoryService.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/middleware/tests/AdminController.test.ts
server/src/service-layer/controllers/AdminController.ts
server/src/service-layer/request-models/AdminRequests.ts
server/src/service-layer/response-models/AdminResponse.ts

Have only the one dealing with date ranges, the one querying by date range should be implemented later - may not even need it due to it being less intuitive to implement on the front-end

create paginated endpoint to fetch all booking history

---

client/src/components/composite/Admin/AdminBookingHistoryView/AdminBookingHistoryItem.story.tsx
client/src/components/composite/Admin/AdminBookingHistoryView/AdminBookingHistoryItem.tsx
client/src/components/composite/Admin/AdminBookingHistoryView/AdminBookingHistoryView.tsx
client/src/components/composite/Admin/AdminBookingView/AdminBookingCreationPopUp.tsx
client/src/services/Utils/Messages.ts

Also implemented a `Messages` util object so that common messages aren't duplicated

726 frontend implement undo functionality for booking deletions

---

client/src/app/sections/LandingSection.tsx

Made sure that we use the `playInline` attribute, and also took into consideration that `webm` may not be supported

Fix videos on ios

---

client/src/app/sections/LandingSection.tsx

* add playsInline attribute to video
* only use webm as fallback

Fix videos on ios release

---

client/src/components/composite/Admin/AdminBookingView/WrappedAdminBookingCreationPopUp.tsx
server/src/middleware/__generated__/swagger.json

alert msg added

---

client/src/components/composite/Admin/AdminBookingView/AdminBookingDateDisplay/AdminBookingDate/AdminBookingDate.tsx
client/src/components/composite/Admin/AdminBookingView/AdminBookingDateDisplay/AdminBookingDate/BookingUserCard.tsx
client/src/components/composite/Admin/AdminBookingView/AdminBookingDateDisplay/AdminBookingDateDisplay.story.tsx
client/src/components/composite/Admin/AdminBookingView/AdminBookingDateDisplay/AdminBookingDateDisplay.tsx
client/src/components/composite/Admin/AdminBookingView/WrappedAdminBookingView.tsx
client/src/services/Admin/AdminUtils.test.ts
client/src/services/Admin/AdminUtils.ts

Sort users by their name, and use 1 indexing on booking view

---

client/src/models/__generated__/schema.d.ts
server/src/data-layer/models/firebase.ts
server/src/data-layer/services/EventService.test.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/middleware/tests/EventController.test.ts
server/src/service-layer/controllers/EventController.ts
server/src/service-layer/request-models/EventRequests.ts

Add a signup timestamp to the EventReservation Type

---

.github/workflows/update_google_sheet_members.yml

Fixes the bug in #791 
Add Install dependencies step

Fix members google sheet workflow

---

server/src/middleware/tests/AdminController.test.ts
server/src/service-layer/controllers/AdminController.ts

* Added parsing in controller for timestamps
* Modified test case to try editing timestamp

Fixed edit event endpoint to properly parse timestamps

---

client/src/models/__generated__/schema.d.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/middleware/tests/AdminController.test.ts
server/src/middleware/tests/EventController.test.ts
server/src/service-layer/controllers/AdminController.ts
server/src/service-layer/controllers/EventController.ts
server/src/service-layer/response-models/AdminResponse.ts
server/src/service-layer/response-models/EventResponse.ts

* Updated endpoint
* Updated interfaces
* Updated tests
* Generate swagger

Scope get event id endpoint to admins only

---

client/src/models/__generated__/schema.d.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/middleware/tests/AdminController.test.ts
server/src/service-layer/controllers/AdminController.ts

Required to fully complete the events view on the frontend

Create DELETE endpoint for events

---

.github/workflows/prune-cloudflare-deployments.yml
server/package.json
server/tooling/prune-cloudflare-deployments.ts

closes #755 
We need this because we literally had 3000 deployments in cloudflare pages, and while this might be ok since its unlimited good luck to whoever revisits this in 2 years!

Implement cleanup script for cloudflare pages

---

client/src/components/composite/Admin/AdminMemberView/ProtectedAdminMemberView.tsx
server/src/service-layer/controllers/AdminController.ts

with the large amount of users in the database we experienced an error where we were hitting the auth quota
see https://stackoverflow.com/a/58028558 which says max per second should be 10 users
To overcome this we use batching

Throttle demote all users to allow for smoother UX

---

client/sanity.config.ts

This fixes the "no tabs found" issue

Add "Policies" document type to Sanity configuration

---

client/src/components/composite/Booking/BookingCreation/BookingCreation.tsx
client/src/components/composite/Booking/BookingCreation/EmergencyContactAlert/EmergencyContactAlert.story.tsx
client/src/components/composite/Booking/BookingCreation/EmergencyContactAlert/EmergencyContactAlert.tsx
client/src/components/composite/Booking/BookingCreation/ProtectedCreateBookingSection.tsx
client/src/store/SignUpForm.tsx

This serves as a safeguard due to this information being the most important for the lodge custodian (in case of something happening at the lodge). Also enforced dietary requirements as that was in backlog

Enforce emergency contact entry on Bookings page

---

client/src/app/sections/AboutSection.tsx
client/src/components/composite/SignUpForm/Sections/AdditionalSection.tsx

…#840)
* use a date object for year
* Update year references in AboutSection and AdditionalSection to use the current year dynamically

Date fix release

---

client/src/store/SignUpForm.tsx

This reverts commit 969768ed0ef78b3a9cd907bab5ef595ee471da3b. Which breaks uni emails

Revert "adding regex for .com (#812)"

---

client/src/components/composite/Admin/AdminEventView/AdminEventForm/AdminEventForm.tsx
client/src/components/composite/EventsView/EventsView.tsx
client/src/components/generic/Event/EventPreview/EventPreview.tsx
client/src/components/generic/Event/EventUtils.ts
client/src/models/__generated__/schema.d.ts
server/src/data-layer/models/firebase.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/middleware/tests/EventController.test.ts
server/src/service-layer/controllers/AdminController.ts
server/src/service-layer/controllers/EventController.ts

Make sign up date non compulsory

---

client/src/components/generic/Event/EventUtils.ts

Update event date formatting to use New Zealand locale

---

client/src/app/HomeComponent.tsx

Fix incorrect message reference in HomeComponent disclaimer

---

client/src/components/composite/Booking/BookingInfoComponent/BookingInfoComponent.tsx

Changes that are not already customizable through stripe:
- Booking Dates
- Booking information
- Booking Email template

Prepare site for booking season

---

client/src/components/composite/Booking/BookingInfoComponent/BookingInfoComponent.tsx
server/src/business-layer/templates/BookingConfirmation.pug

Revision PR:
> changed some stuff and added 3 links. One at the start for the snow report, one for the link to the policy, and replaced the wellbeing link at the bottom with the current one.

Booking season prep

---

client/src/components/composite/Booking/BookingInfoComponent/BookingInfoComponent.tsx
client/src/components/composite/Contact/ContactDetailPanel/ContactDetailPanel.tsx
client/src/components/generic/ContactDetail/ContactDetail.story.tsx
client/src/components/generic/ContactDetail/ContactDetail.tsx
client/src/models/sanity/ContactDetail/Schema.ts
client/src/models/sanity/ContactDetail/Utils.ts

Add links to contact detail schema

---

client/src/app/sections/BenefitSection.tsx
client/src/components/generic/MemberBenefitCards/MemberBenefitCard.tsx

Design/UX debt fixed where too much of image was being covered and having inconsistent corner rounding

Refactor benefit section to use MemberBenefitCard component for imprved structure and styling

---

.github/workflows/cd-pipeline.yml

Fixes the typo of `var` instead of `vars`. Has been tested and deploys. 
Fixes #876

build: use vars context for deployment URL

---

.github/workflows/cd-pipeline.yml

This fixes the CD pipeline issue where the action type was a text box instead of a dropdown. 
Fixes #876

fix: add workflow choice type to cd pipeline

---

.github/cd-actions/deploy-server/action.yml
.github/cd-actions/setup-host/action.yml

Should terminate the script now since we have `set -e` set in the bash shebang. 
Fixes #903

fix(cd): add `set -e` to deploy scripts

---

client/src/components/utils/PortableTextRender/PortableTextRenderer.tsx

This PR updates the `PortableTextRenderer` component to be a memoized React component using `React.memo`. This optimization prevents unnecessary re-renders when props remain unchanged, improving performance particularly for large or frequently updated portable text content.
- Wrapped the `PortableTextRenderer` function component with `React.memo`
- No modifications to component's API or rendering logic
- Optimizes React rendering by preventing redundant renders when input props remain the same
- Particularly beneficial in scenarios where:
- Component is used multiple times
- Component handles large datasets
✅ No breaking changes  
✅ Improved performance for component consumers  
✅ No changes required for existing usage
- ✓ Verified component renders correctly
- ✓ Confirmed re-renders are …

fix: prevent unnecessary re-renders in PortableTextRenderer by wrapping with React.memo

---

.github/workflows/cd-pipeline.yml
.github/workflows/ci-pipeline.yml

Properly set the environment variable for the google sheet. Right now only planning on populating it in prod

fix: use secret for REDIRECT_MEMBERS_GOOGLE_SHEET_LINK in CD pipeline configuration
