frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/firebase.js

Exports the `db` item from the `firebase/firestore` package in `firestore.js`. This allows other files (such as `App.js`) to use the Firestore to perform database queries.
Implements a base query to retrieve a sample user from the Firestore.

Add firestore setup

---

frontend/src/App.js
frontend/src/components/Navbar.js
frontend/src/pages/Home.js

Completed:
- Navbar is now sticky so it remains in view as the user continues to scroll down a page.
- Navbar is hidden by default when visiting the home page and is only displayed when the user has scrolled more than a certain proportion (currently set to 30% but can be easily changed) of the view height. The navbar also hides again if the user scrolls back up to the top of the home page.
Notes:
- This behaviour is only present on the home page - on every other page the navbar is shown by default and doesn't show/hide on scroll.

Uasc 35/auto hide navbar on home page

---

frontend/src/firebase.js

We hook into the native feature of create-react-app which sets the `NODE_ENV` environment variable to be `development` when running `npm start`, and `production` when running `npm run build` (as we do when deploying).
This allows us to toggle between using the emulator suite, or the production store.

Fix production build of emulator suite

---

frontend/ARCHITECTURE.md

Adds some documentation describing the way the `requests` collection is structured in Firestore.
Closes #56

Document requests database

---

frontend/ARCHITECTURE.md

Documents the structure of the `bookings` and `booking_changes` collection that exist in Firestore.
I elected to not have a `booking_dates` for now as it seems that Firestore will [automatically index](https://firebase.google.com/docs/firestore/query-data/index-overview#an_index_behind_every_query) our queries, which should alleviate the pain of efficiently reading dates.

Add documentation of bookings collection

---

frontend/firestore.rules

Extends read access to the Firestore up until October 22th. This should give us enough time until we deploy proper read rules.

Extend Firestore rules all-read access

---

frontend/ARCHITECTURE.md
frontend/src/components/ProfileCalendarCard.js
frontend/src/components/ProfileCard.js
frontend/src/components/ProfileCurrentBookings.js
frontend/src/pages/Profile.js

We now display the user bookings on the `/profile` page, which shows:
1. a calendar overview with highlighted dates they have booked
2. a list of all their current bookings (alongside the request changes button)

Display user bookings in profile page

---

client/src/components/composite/SignUpForm/SignUpForm.story.tsx
client/src/components/composite/SignUpForm/SignUpForm.tsx

get storybook working for signup form

---

client/src/firebase.ts
client/src/models/User.ts
client/src/store/store.ts

closes #141 
We now have our user data stored in sweet state.
This is similar to the work @8cw did in the `useAuthenticatedUser` hook, but this one gets triggered on the id token changing for the user in auth
There are two objects stored: `currentUser`, which is a reference to the user object from the firebase auth and `currentUserData`, which is of type `UserAdditionalInfo` (which is similar to the `userMetaData` in the old hook)
to use this user in components, use `const [{currentUser, currentUserData, currentUserClaims}] = useAppData()` (you can exclude properties you aren't using)
from there you can call functions like: `await currentUser.getIdToken(true)` to refresh the user. Or access the information/claims by using `currentUserData`/`currentUserClaims`

store current user in sweet state

---

package.json

Adds [https://volta.sh/](https://volta.sh/) configuration to package.json as an alternative to nvm.
Volta is used by other repositories such as TypeScript to manage the toolchain of package managers.
We could consider changing the onboarding flow for future contributors to simply be:
- install Volta with something akin to `curl https://get.volta.sh | bash`
- now both `node` and `yarn` are installed, and enforced to be the same version across everyone who contributes
This would remove our need to have people go through corepack to install yarn.

Add volta to repository

---

client/src/firebase.ts

Previously we would perform a `getIdTokenResult()`, followed by a `getIdToken()` call. This is two API calls to Firebase, and can be simplfied by using the `token` property from the resutl of `getIdTokenResult()`.
Also updates the `onIdTokenChanged` flow to handle errors more gracefully, by `return`ing early if we are unable to retrieve the token details (rather than setting `null` data to memory.
Observing the source of `getIdTokenResult` at
https://github.com/firebase/firebase-js-sdk/blob/6d31930b3abe1588ae81a5c14b59cd386fddc718/packages/auth/src/core/user/id_token_result.ts#L55-L88 it is evident that it calls `getIdToken` internally.
See https://github.com/firebase/firebase-js-sdk/blob/6d31930b3abe1588ae81a5c14b59cd386fddc718/packages/auth/src/core/user/user_impl.ts#L102-L116 for the …

Refactor double-fetch for token changes

---

client/src/pages/Register/Register.tsx

We had an issue where `confirmEmail` was being part of the payload for the `signup` endpoint, causing validation to fail.

Refactor user schema

---

client/src/models/__generated__/schema.d.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/middleware/routes.test.ts
server/src/service-layer/controllers/AdminController.ts
server/src/service-layer/response-models/BookingResponse.ts

Mostly a copy-paste job of #349, added extra test to make sure it works for skipped dates:
i.e
```
has booking slot / no booking slot / has booking slot
```
Also refactored the names to be plural instead
Is needed for (is blocking) #390

Allow admins to make dates unavailable using endpoint

---

client/src/models/__generated__/schema.d.ts
server/src/business-layer/utils/BookingConstants.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/middleware/routes.test.ts
server/src/service-layer/controllers/AdminController.ts
server/src/service-layer/request-models/AdminRequests.ts

There is the use case for when admins want to make a date available with less than the default (32) spots (such as pre booked dates). To solve this an *optional* parameter has been added to the request body. New tests have been added to make sure it:
- Overwrites old values
- Still applies the default in case of undefined

Allow make available endpoint to take in custom slots

---

client/src/components/composite/Admin/AdminMemberView/AdminMemberView.tsx
client/src/components/composite/Admin/AdminMemberView/ProtectedAdminMemberView.tsx
client/src/components/generic/ReusableTable/Table.tsx
client/src/models/__generated__/schema.d.ts
client/src/services/Admin/AdminQueries.ts
client/src/services/Admin/AdminService.ts
client/src/utils/Constants.ts
server/src/business-layer/services/AuthService.test.ts
server/src/business-layer/services/AuthService.ts
server/src/business-layer/utils/AuthServiceClaims.ts
server/src/data-layer/services/UserDataService.test.ts
server/src/data-layer/services/UserDataService.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/middleware/routes.test.ts
server/src/service-layer/controllers/AdminController.ts
server/src/service-layer/controllers/UserController.ts
server/src/service-layer/response-models/CommonResponse.ts
server/src/service-layer/response-models/UserResponse.ts

closes #149 
Have also implemented pagination as this would be limited to 100 user objects/request
Data omitted due to real information 
- New callback `onPageChange` which notifies of when an attempt should be made for fetching the next "page" of data
-  Introduced base types for paginated responses in `CommonResponse` - note a cursor based one exists as firestore doesn't support offset based
- Switched to `useInfiniteQuery` to allow for easier pagination on FE

400 frontend make all users endpoint return correct fields + paginate

---

client/src/components/composite/SignUpForm/PageConfig/PageConfig.tsx
client/src/hooks/useRefreshedToken.ts
client/src/pages/Booking.tsx
client/src/pages/Profile/Profile.tsx
client/src/pages/Register/Register.tsx

Have called the store action created in #284 on the:
- `bookings` 
- `profile`
pages so that the user can see up to date information about the views.
The user may now *not* navigate away from the payment confirmation page until their account has been logged back in by firebase

Refresh user tokens on pages that require it

---

client/src/components/composite/Booking/BookingCreation/BookingCreation.tsx
client/src/components/utils/Utils.tsx
client/src/services/Payment/PaymentService.ts
server/src/business-layer/services/StripeService.ts
server/src/business-layer/utils/BookingUtils.ts
server/src/service-layer/controllers/PaymentController.ts

The problem before is the different timezones on the frontend return different dates from the date inputs. The fix here is to use `getDay` on the front end (to display the appropriate data to the user) and backend **but** on the back end need to re-parse the date to its timezone to account for differences. 
- Switch to getDay instead of getUTCDay (helps to resolve the issue of dates getting "pushed back" one day)
- Add check on frontend to disallow selection of 10 > nights
- Display the dates the current booking is for in the checkout session

Improve date handling on frontend

---

client/src/components/composite/Admin/AdminMemberView/AdminMemberView.tsx
client/src/components/composite/Admin/AdminMemberView/ProtectedAdminMemberView.tsx
client/src/components/generic/ReusableTable/Table.tsx
client/src/services/Admin/AdminMutations.ts
client/src/services/Admin/AdminService.ts
server/src/service-layer/controllers/UserController.ts

Had to make some changes to the endpoint made in #408, because in some cases we still want to carry out all the steps even if the previous ones failed. Also introduced an `isUpdating` prop to give feedback that a deletion is happening

Allow admins to delete users

---

server/src/service-layer/controllers/PaymentController.ts

The changes in #463 meant that while the bookings were functionally correct, the displayed dates to the user were wrong. This is why we have to normalise the dates to make the correct ones displayed (to be consistent with the ones in admin view - #431 for further discussion)

format dates properly for display

---

client/src/components/composite/SignUpForm/Sections/PersonalSection.tsx

Before we weren't checking if the value was undefined, also added appropriate limits to ages

Fix date of birth input crashing site

---

.github/workflows/deploy-client-production.yml
.github/workflows/deploy-server.production.yml

The prod deployment wouldn't run due to missing `}` and also remade the environements to be more specific

Fix typo in prod server workflow, and update the environments associated with each

---

client/package.json
client/src/App.tsx
client/src/pages/RefreshNotification/RefreshNotification.story.tsx
client/src/pages/RefreshNotification/RefreshNotification.tsx
yarn.lock

Now when an error is thrown the user will be told to refresh the page instead of getting a blank screen.

add error boundary for components

---

client/src/components/composite/Booking/BookingCreation/BookingCreation.story.tsx
client/src/components/composite/Booking/BookingCreation/BookingCreation.tsx
client/src/components/composite/Booking/BookingInfoComponent/BookingInfoComponent.tsx
client/src/utils/Constants.ts

The client is worried about people misinterpreting the dates they are booking, so we have added an extra confirmation

Confirm the users dates (actual check in and check out) on bookings page

---

.github/workflows/deploy-client-production.yml
.github/workflows/deploy-client-stable.yml

Added the new workflow and enabled cron schedule to update stable branch to the production app.
Removed the cron schedule from the master workflow, can only manually update production through master.

639 Add Cron Workflow to Deploy Stable

---

server/src/business-layer/services/StripeService.ts
server/src/service-layer/controllers/PaymentController.ts

Removed `hasProcessingPaymentIntent` from StripeService.ts 
Removed corresponding check in the endpoint.
Closes #287

287 Remove payment intent check in membership payment

---

server/package.json
server/src/business-layer/services/MailService.ts
server/tsconfig.json

Right now the backend fails to use the template because it can't compile
Also made the compile function last the app lifetime, do not need to be constantly recompiling.

copy templates to build outputs

---

client/src/components/generic/ReusableTable/Table.story.tsx
client/src/components/generic/ReusableTable/Table.tsx

To make use of this you will need to pass in the row identifier, like documented in the `@example`

allow clicking table row to invoke callback

---

server/src/middleware/tests/BookingController.test.ts
server/src/service-layer/controllers/BookingController.ts

before the check meant that users couldn't be added if they had a booking, but that was not specific to the range.

fix booking creation if user already has a booking

---

client/src/app/admin/layout.tsx

Right now the redirects does not play nicely with SSG, as the auth state seems to reset when the page is lazy-loaded.
We assume the only people accessing this route are admins, and if its is not, then an infinite loader is an acceptable experience.

remove hard redirect on admin pages to improve UX

---

client/src/utils/Constants.ts
server/src/business-layer/services/StripeService.ts
server/src/business-layer/templates/BookingConfirmation.pug
server/src/business-layer/utils/BookingUtils.test.ts
server/src/business-layer/utils/BookingUtils.ts
server/src/service-layer/controllers/AdminController.ts

> Can it show the day after, the same as how booking conf on website page shows the date after
Added relevant helper functions and changed formatting everywhere
also changed check in to `11:00am`

Format the booking confirmation to be explicit about check in/out

---

server/src/data-layer/adapters/FirestoreCollections.ts
server/src/data-layer/models/firebase.ts

Will need to document this in wiki - hold off on merge until then.

implement booking history collections

---

client/sanity.config.ts
client/sanity/schema.ts
client/src/models/sanity/LodgeInfo/Schema.ts
client/src/models/sanity/LodgeInfo/Utils.ts

We will have to create a renderer for rich text blocks, likely involving one of the following:
- https://github.com/sanity-io/block-content-to-react/issues/26
- https://github.com/portabletext/react-portabletext

add the lodge info schema to sanity

---

client/sanity/lib/utils.ts
client/src/app/about/page.tsx
client/src/app/sections/BenefitSection.tsx

https://www.sanity.io/answers/optimizing-image-file-sizes-in-studio-and-using-url-parameters-for-width-and-format-
created server compatible class called `SanityImageUrl` in `client/sanity/lib/utils.ts` to allow for basic manipulation of the image urls.

Convert sanity images to webp in attempt to improve page loads

---

client/src/components/composite/Admin/AdminBookingView/AdminBookingDateDisplay/AdminBookingDate/AdminBookingDate.story.tsx
client/src/components/composite/Admin/AdminBookingView/AdminBookingDateDisplay/AdminBookingDate/AdminBookingDate.tsx
client/src/components/composite/Admin/AdminBookingView/AdminBookingDateDisplay/AdminBookingDate/BookingUserCard.story.tsx
client/src/components/composite/Admin/AdminBookingView/AdminBookingDateDisplay/AdminBookingDate/BookingUserCard.tsx
client/src/components/composite/Admin/AdminBookingView/AdminBookingDateDisplay/AdminBookingDateDisplay.story.tsx
client/src/components/composite/Admin/AdminBookingView/AdminBookingDateDisplay/AdminBookingDateDisplay.tsx
client/src/components/composite/Admin/AdminBookingView/AdminBookingView.tsx
client/src/components/composite/Admin/AdminBookingView/WrappedAdminBookingView.tsx
client/src/services/Utils/Messages.ts

`Table` is fully removed for a more user-friendly experience

New design for booking table

---

client/package.json
client/sanity/lib/utils.ts
client/src/app/bookings/page.tsx
client/src/components/composite/Booking/BookingCreation/BookingCreation.tsx
client/src/components/composite/Booking/BookingCreation/ProtectedCreateBookingSection.tsx
client/src/components/composite/Booking/BookingInfoComponent/BookingInfoComponent.tsx
client/src/components/composite/Booking/BookingInformationAndCreation/BookingInformationAndCreation.story.tsx
client/src/components/composite/Booking/BookingInformationAndCreation/BookingInformationAndCreation.tsx
client/src/components/composite/LodgeInfo/LodgeInfo.tsx
client/src/models/sanity/LodgeInfo/Utils.ts
yarn.lock

Added new dependency https://www.npmjs.com/package/@portabletext/react to help render the text blocks (typed by `PortableTextBlock`. This should be used for any schema that requires rich text in the future - may be relevant for #631. 
also deprecated `ProtectedCreateBookingSection` as now `BookingInformationAndCreation` should be used instead

660 frontend put lodge schemas on bookings page

---

client/src/app/bookings/page.tsx

This fixes the error in case nothing is fetched from sanity

Fix build errors due to undefined access

---

client/src/components/composite/LoginForm/LoginForm.tsx

added message when user logged into their account

---

client/src/components/composite/Admin/AdminBookingView/AdminBookingView.tsx

We now display the total number of bookings next to the date range

768 frontend display total bookings on admin view

---

client/src/app/bookings/page.tsx
client/src/components/composite/LodgeInfo/LodgeInfo.story.tsx
client/src/components/composite/LodgeInfo/LodgeInfo.tsx
client/src/components/composite/LodgeInfo/LodgeInfoComponent/LodgeInfoComponent.tsx
client/src/components/composite/LodgeInfo/LodgeInfoGallery/LodgeInfoGallery.story.tsx
client/src/components/composite/LodgeInfo/LodgeInfoGallery/LodgeInfoGallery.tsx

Right now the problem with the current one is that it does not play well on smaller screens, and the photo gallery is pretty hard to use. To solve this it makes more sense to keep styling simpler.
- Simplified gallery to just horizontally scroll
- Only use one column
- Add button to skip the lodge information

Restyle lodge booking page to be more robust

---

client/src/models/__generated__/schema.d.ts
server/src/data-layer/services/EventService.test.ts
server/src/data-layer/services/EventService.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/middleware/tests/EventController.test.ts
server/src/service-layer/controllers/EventController.ts
server/src/service-layer/request-models/EventRequests.ts
server/src/service-layer/response-models/EventResponse.ts

Created new eventSignup endpoint and their controller.
Takes in a EventSignupBody and returns an EventSignupResponse.
Created EventService `getAllReservations` method and test.

Add eventSignup endpoint and new getAllReservations EventService method.

---

client/src/models/__generated__/schema.d.ts
server/src/data-layer/models/firebase.ts
server/src/data-layer/services/BookingHistoryService.ts
server/src/data-layer/services/EventService.test.ts
server/src/data-layer/services/EventService.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/middleware/tests/AdminController.test.ts
server/src/middleware/tests/EventController.test.ts
server/src/service-layer/controllers/AdminController.ts
server/src/service-layer/controllers/EventController.ts
server/src/service-layer/request-models/EventRequests.ts
server/src/service-layer/response-models/EventResponse.ts

created two endpoints:
- `GET /events`
- Allows users to do cursor based pagination on the latest events
- `POST /admin/events`
- Simple **create** operation
Note the changes used for sorting timestamps in `server/src/data-layer/services/EventService.ts` need to be implemented in `BookingHistory` as the are currently not being sorted properly :skull:.

backend create endpoint for admin to create event and also to fetch all events

---

client/src/models/__generated__/schema.d.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/middleware/tests/AdminController.test.ts
server/src/service-layer/controllers/AdminController.ts

* Created new endpoint PATCH events/{id}
* Created tests

Create endpoint for admins to edit an event

---

server/src/data-layer/services/EventService.test.ts
server/src/data-layer/services/EventService.ts
server/src/service-layer/controllers/AdminController.ts
server/src/service-layer/controllers/EventController.ts

I've changed the method in the controller to use the modified method.
Also changed EventService to return a Record instead of just a number.
Updated tests

Rewrite SSE endpoint to return map of reservations per event ID

---

client/src/models/__generated__/schema.d.ts
server/src/data-layer/models/firebase.ts
server/src/data-layer/services/EventService.test.ts
server/src/data-layer/services/EventService.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/middleware/tests/AdminController.test.ts
server/src/middleware/tests/EventController.test.ts
server/src/service-layer/controllers/AdminController.ts

This is because we are removing the firestore signups for events in #797. This field is also optional so the event can be created pretty far out from the sign up date.
Renamed the `start_date` and `end_date` to `sign_up_start_date` and `sign_up_end_date` to fix the bad naming

Add google forms link as field to event and clarify fields

---

client/src/models/__generated__/schema.d.ts
server/src/data-layer/adapters/FirestoreSubcollections.ts
server/src/data-layer/models/firebase.ts
server/src/data-layer/services/EventService.test.ts
server/src/data-layer/services/EventService.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/middleware/tests/EventController.test.ts
server/src/service-layer/controllers/EventController.ts
server/src/service-layer/request-models/EventRequests.ts
server/src/service-layer/response-models/EventResponse.ts

* Deleted event signup endpoint
* Deleted SSE endpoint
* Removed relevant endpoint tests
* Remove EventReservation service methods and tests
* Remove event reservations from firebase and subcollection
* Note that `Event.max_occupancy` is kept as this could still be useful.
* Also note that `FirestoreSubcollections.ts` was kept as this could be used in the future.
* Also removed the event request for signup

797 backend delete all code relating to event sign ups

---

client/src/firebase.ts
client/src/services/Storage/StorageService.ts

same issue as https://github.com/vercel/next.js/discussions/11351https://github.com/vercel/next.js/discussions/11351, however we just need to not call `getStorage` raw without passing in the firebase app
This was causing the `admin/events` build to sometimes fail

fix double initialistation of firebase when creating storage service

---

client/src/components/composite/Admin/AdminEventView/AdminEventForm/AdminEventForm.story.tsx
client/src/components/composite/Admin/AdminEventView/AdminEventForm/AdminEventForm.tsx
client/src/components/generic/Event/EventPreview/EventPreview.tsx
client/src/components/generic/Event/EventUtils.test.ts
client/src/components/generic/Event/EventUtils.ts

Added two props to the `AdminEventForm`:
- `isEditingMode`
- `defaultData`
Which allow the form to be used to send edit requests with the `PATCH` endpoint for events
>[!NOTE]
>Also fixed the padding in the Event Preview, because the use of numbers conditionally stopped tailwind from being compiled properly

allow form to be used for both editing and creating

---

client/src/components/composite/Admin/AdminEventView/AdminAllEvents/AdminAllEvents.tsx
client/src/components/composite/Admin/AdminEventView/AdminEventForm/AdminEventForm.tsx
client/src/components/composite/Admin/AdminEventView/AdminEventView.story.tsx
client/src/components/composite/Admin/AdminEventView/AdminEventView.tsx
client/src/components/composite/Admin/AdminEventView/WrappedAdminEventView.tsx
client/src/components/composite/EventsView/EventsView.tsx
client/src/components/generic/Event/EventUtils.test.ts
client/src/components/generic/Event/EventUtils.ts
client/src/models/Events.ts
client/src/services/Admin/AdminMutations.ts
client/src/services/Admin/AdminQueries.ts
client/src/services/Admin/AdminService.ts
client/src/services/Event/EventQueries.ts
server/src/middleware/tests/EventController.test.ts
server/src/service-layer/controllers/EventController.ts

Made use of the work in #815, and created the new queries for fetching a single event (waiting for #817) and mutation for editing the event. 
Have added placeholders for the delete functionality, which an endpoint needs to be made for
Also fixed a logical error in #799 where it was checking the event start date instead of sign up start date

816 frontend implement editing functionality for events

---

client/src/components/composite/Admin/AdminEventView/AdminEventView.tsx
client/src/components/composite/Admin/AdminEventView/WrappedAdminEventView.tsx
client/src/services/Admin/AdminMutations.ts
client/src/services/Admin/AdminService.ts

Now admins have a fully usable events management system!
Made some small code quality changes to invalidate the events queries but otherwise is done.

Allow events to be deleted on edit view

---

client/src/components/composite/Admin/AdminEventView/AdminEventView.tsx
client/src/services/Admin/AdminMutations.ts

With this change we now assume that all events are invalid and refetch the whole list, note that this is pretty much the same performance as before anyway - but stops the user from accessing out-of-date data.

Properly refresh the list of events after being refetched

---

client/src/components/composite/Admin/AdminMemberView/AdminMemberView.story.tsx
client/src/components/composite/Admin/AdminMemberView/AdminMemberView.tsx
client/src/components/composite/Admin/AdminMemberView/ProtectedAdminMemberView.tsx
client/src/services/Admin/AdminMutations.ts
client/src/services/Admin/AdminService.ts
server/src/service-layer/controllers/AdminController.ts

allow admins to reset all memberships on front end

---

server/tooling/update-google-sheet-members.ts

The action was previously not working properly due to the function saying:
```
Failed to add rows to the google sheet. GaxiosError: This action would increase the number of cells in the workbook above the limit of 10000000 cells.
```
This will now fix the error by overwriting instead of constantly extending the sheet
(Refer to https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/append#InsertDataOption)

Use "overwrite" instead of "insert rows" to fix sheet overflow error 

---

client/src/components/composite/SignUpForm/Sections/PersonalSection.tsx
client/src/store/SignUpForm.tsx
server/tooling/update-google-sheet-members.ts

Also updated the google forms script, as it was not previously showing the student id
note that the `student_id` field has a new meaning now - all presentations of it should refer to UPI now!

Make UPI Mandatory when signing up

---

client/src/app/sections/AboutSection.tsx
client/src/components/composite/SignUpForm/Sections/AdditionalSection.tsx

Had a problem where it still showed the old year

use a date object for year so that 2024 will not need to be updated

---

client/src/app/events/page.tsx
client/src/components/composite/Admin/AdminEventView/AdminEventForm/AdminEventForm.test.tsx
client/src/components/composite/Admin/AdminEventView/AdminEventForm/AdminEventForm.tsx
client/src/components/composite/Admin/AdminEventView/WrappedAdminEventView.tsx
client/src/components/composite/EventsView/EventsView.tsx
client/src/components/generic/Event/EventDetailed/EventDetailed.tsx
client/src/components/generic/Event/EventPreview/EventPreview.tsx
client/src/components/generic/Event/EventUtils.ts
client/src/components/generic/Event/EventUtils/EventUtils.tsx
client/src/models/__generated__/schema.d.ts
client/src/services/Event/EventQueries.ts
client/src/services/Event/EventService.ts
server/src/data-layer/models/firebase.ts
server/src/middleware/__generated__/routes.ts
server/src/middleware/__generated__/swagger.json
server/src/middleware/tests/EventController.test.ts
server/src/service-layer/controllers/EventController.ts

Some events should not show the google form link if it is restricted to members. This PR allows admin the option to hide the link and only allow fetching if admin
**Unauthed**
**Authed**
**Admin Option**

Allow members only events

---

client/sanity.config.ts
client/sanity/schema.ts
client/src/app/shop/layout.tsx
client/src/app/shop/page.tsx
client/src/components/composite/Navbar/Navbar.tsx
client/src/components/composite/ShopView/ShopView.story.tsx
client/src/components/composite/ShopView/ShopView.tsx
client/src/components/generic/Shop/ProductImage/ProductImage.story.tsx
client/src/components/generic/Shop/ProductImage/ProductImage.tsx
client/src/components/generic/Shop/ProductInfo/ProductInfo.story.tsx
client/src/components/generic/Shop/ProductInfo/ProductInfo.tsx
client/src/components/generic/Shop/ShopItem.story.tsx
client/src/components/generic/Shop/ShopItem.tsx
client/src/models/sanity/ShopItem/Schema.ts
client/src/models/sanity/ShopItem/Utils.ts

- Created a new Sanity schema for shop items to enable e-commerce functionality
- Implemented ShopItemSchema with fields for product details including:
- Item name
- Main and secondary images
- Google Form link for purchases
- Display price
- Item description
The UASC website already has a shop page accessible from the navigation bar but lacked the backend infrastructure to manage product listings. This PR introduces the content model in Sanity CMS needed to support the online shop, where products will be purchased through Google Forms rather than a traditional checkout system.
Closes #853

Add shop layout and components for displaying merchandise

---

.github/workflows/deploy-server.production.yml
.github/workflows/deploy-server.staging.yml

Renamed from `REDIRECT_MEMBERS_GOOGLE_SHEET` to `REDIRECT_MEMBERS_GOOGLE_SHEET_LINK`
in accordance with `server/src/business-layer/utils/RedirectKeys.ts`

Update Google Sheet secret variable names in deployment configurations

---

.github/ci-actions/build-client/action.yml
.github/ci-actions/build-server/action.yml
.github/ci-actions/codegen/action.yml
.github/ci-actions/firebase-preview/action.yml
.github/ci-actions/lint/action.yml
.github/ci-actions/prettier/action.yml
.github/ci-actions/setup/action.yml
.github/ci-actions/test/action.yml
.github/workflows/deploy-client-production.yml
.github/workflows/deploy-client-staging.yml

Adds restore keys to all actions so that upon cache miss, it'll follow the cache restore keys in order. 
This was implemented because the recent CI run failed in `master` because somehow the cache keys weren't found, hence restore keys can be used (the cache keys are looked up by date). 
Fixes # (issue)

ci: add restore keys for pnpm cache

---

.github/workflows/deploy-client-production.yml

We should not set the environment flag because we are not using any of the cloudflare worker secrets - please see https://github.com/cloudflare/wrangler-action?tab=readme-ov-file#configuration

fix: remove environment specification from wrangler action in deployment config

---

biome.json
client/src/app/bookings/page.tsx
client/src/components/utils/PortableTextRenderer.tsx

This PR introduces and enforces a standardized approach for rendering PortableText content across the codebase, ensuring consistent styling, accessibility, and adherence to the design system.
- **Created/Updated `PortableTextRenderer` Component**
- Centralizes all PortableText rendering logic.
- Applies Tailwind classes for accessible, readable, and design-system-compliant typography.
- Supports props for overriding header and text color classes (`headerColorClass`, `textColorClass`).
- Ensures consistent line height and font styling for paragraphs and list items.
- **Restricted Direct Import of `@portabletext/react`**
- Added a comment in `PortableTextRenderer.tsx` to warn against direct imports.
- Updated `biome.json` to add a linter rule (`noRestrictedImports`) that throws an error if …

feat: add PortableTextRenderer for consistent rich text styling and replace direct PortableText usage

---

client/src/components/composite/Profile/ProfileEdit/ProfileEdit.test.tsx
client/src/components/composite/Profile/ProfileEdit/ProfileEdit.tsx

- Added comprehensive unit tests for the ProfileEdit component
- Improved accessibility by adding proper ARIA labels and input IDs
- Fixed checkbox default value handling for boolean fields
- Enhanced close button implementation with proper semantic HTML
- Added unique IDs for form fields to ensure proper label associations
- Test coverage for component rendering, form submission, and close functionality
- Proper handling of various field types (text, boolean, date)
- Improved form field accessibility with unique IDs and labels
Added test cases for:
- Component rendering with all field types
- Form submission with updated values
- Close button functionality
- Used React Testing Library for component testing
- Implemented proper event handling for form submission and close actions
- …

fix: persist boolean field values in profile edit modals and improve accessibility of close button

---

.github/workflows/cd-pipeline.yml

Currently we are getting a lot of staging builds failing because of a race condition of the server deploying while the client is also building. This change makes sure that all server deployments have do be performed manually
Fixes # (issue)

fix: make server deployment manual by updating workflow condition
